"""nom des analyses

Revision ID: 1436e85304b1
Revises: 346c000e5787
Create Date: 2026-09-23 11:16:56.198821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1436e85304b1'
down_revision = '346c000e5787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nom', sa.String(), nullable=False, server_default='Sans nom'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_column('nom')

    # ### end Alembic commands ###
