"""listes de mots : word_lists, word_entries

Revision ID: 346c000e5787
Revises: 7b70f94273c6
Create Date: 2026-09-21 15:15:11.125884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346c000e5787'
down_revision = '7b70f94273c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('langue', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom', 'langue')
    )
    op.create_table('word_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_list_id', sa.Integer(), nullable=False),
    sa.Column('expression', sa.String(), nullable=False),
    sa.Column('remplacement', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['word_list_id'], ['word_lists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word_list_id', 'expression')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_entries')
    op.drop_table('word_lists')
    # ### end Alembic commands ###
